# Language setting (ru, en, de, etc.)
language: en

# Default message when no duty role is configured
default-access-message: "&cТвоя роль не настроена."

# Admins display format
admins-list-format: "%status% %name% [%rank%&r] – %duty%"
hide-format: "&kСкрыт&f"

duty-levels:

  moderator:
    permission: unsubduty.role.moderator
    to-group: moderator
    rank-name: "&aModerator"
    priority: 2
    join-message: "&aТы вошёл как Модератор"
    leave-message: "&cDuty отключён"
  
  admin:
    permission: unsubduty.role.admin
    to-group: admin
    rank-name: "&cAdministrator"
    priority: 3
    join-message: "&aПрава Администратора получены"
    leave-message: "&cПрава Администратора отозваны"
  
  senior:
    permission: unsubduty.role.senior
    to-group: senior
    rank-name: "&6Senior Admin"
    priority: 4
    join-message: "&aПрава Старшего Администратора получены"
    leave-message: "&cПрава Старшего Администратора отозваны"
  
  head:
    permission: unsubduty.role.head
    to-group: head
    rank-name: "&4Head Admin"
    priority: 5
    join-message: "&aПрава Главного Администратора получены"
    leave-message: "&cПрава Главного Администратора отозваны"
